package day_3_xml_fileUpload_recap;

import com.github.javafaker.Faker;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Assert;
import org.junit.Test;
import utilities.CashwiseAuthorization;
import utilities.Config;

import java.util.HashMap;
import java.util.Map;


public class ProductControllerTest {
    String token = CashwiseAuthorization.getToken();

    @Test
    public void test1_createNewProduct() {
        /*
        generate new product and gt id
        use faker class to generate data
         */
        String url = Config.getProperty("baseUrl") + "/api/myaccount/products/";

        Faker faker = new Faker();
        String productTitle = faker.commerce().productName();
        double productPrice = faker.number().numberBetween(100, 500);
        int serviceTypeId =2;
        int categoryID = 805;
        String productDescription = faker.commerce().productName() + " company";

//        System.out.println("Product name: " + productTitle);
//        System.out.println("random number for product price: " + productPrice);
//        System.out.println("Product description " + productDescription);

        System.out.println("my token " + token);

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("product title", productTitle);
        requestBody.put("product_price", productPrice);
        requestBody.put("service_type_id", serviceTypeId);
        requestBody.put("category_id", categoryID);
        requestBody.put("product_description", productDescription);

        Response response = RestAssured.given()
                .auth()
                .oauth2(token)
                .contentType(ContentType.JSON)
                .body(requestBody)
                .post(url);

        response.prettyPrint();

        String productID = response.jsonPath().getString("product_id");
        System.out.println("=====================================");
        System.out.println(productID);

        /*
        get exact product you generated by ID
        use get request
        with jsonPath() get productTitle, productPrice, description
         */

        String url2 = Config.getProperty("baseUrl")+"/api/myaccount/products/" + productID;
        Response response1 = RestAssured.given().auth().oauth2(token).get(url2);
//        response1.prettyPrint();

        String actualProductTitle1 = response1.jsonPath().getString("product_title");
        String actualProdPrice1 = response1.jsonPath().getString("product_price");
        String actualDescription1 = response1.jsonPath().getString("product_description");

        System.out.println("NEW product1: " + actualProductTitle1 + " " + actualProdPrice1 + " " + actualDescription1 );

        Assert.assertEquals("Product title is not correct",productTitle, actualProductTitle1);
        Assert.assertEquals("Product price is not correct",productPrice+"", actualProdPrice1);
        Assert.assertEquals("Product description is not correct",productDescription, actualDescription1);
        }
    }

